#!/usr/bin/env bash
# secret-scan.sh — read-only scan for leaked secrets in the working tree and git history.
# Generated by create-secret-scan; tuned for THIS project via the values filled in below.
set -uo pipefail
cd "$(git rev-parse --show-toplevel)" || exit 1

# --- Project-specific configuration (filled in at generation time) ---------

# Pathspecs excluded from plaintext-pattern scans. Always exclude this skill's own
# directory (its docs legitimately contain example secret patterns) plus whatever
# the project's encrypted-secrets directory is, if any.
EXCLUDE=(':!.claude/skills/' ':!node_modules/' ':!dist/')

# Encrypted-secret integrity check (pass 2). If the project has no dedicated
# secret-encryption scheme (sops, git-crypt, transcrypt, ...), leave both blank —
# pass 2 becomes a no-op.
ENCRYPTED_GLOB=""      # no encrypted-secret scheme in this project
ENCRYPTED_MARKERS=""

# Scan full git history (pass 3)? "yes" or "no" — expensive on large/old repos.
SCAN_HISTORY="yes"

# Extra project-specific patterns, appended to the generic baseline below.
# Format: one "description::ERE-pattern" per array element. Leave empty if none.
EXTRA_PATTERNS=()

# Extensions/globs that should be in .gitignore for this project (pass 4, informational).
GITIGNORE_PATTERNS=(".env" "*.pem" "*.key")

# --- Generic high-signal baseline (learned from prior art; broadly applicable) ---

PRIV_BLOCK='-----BEGIN ([A-Z]+ )?PRIVATE KEY-----'
AWS_KEY='AKIA[0-9A-Z]{16}'
GH_TOKEN='gh[pousr]_[A-Za-z0-9]{30,}'
SLACK_TOKEN='xox[baprs]-[A-Za-z0-9-]{10,}'
PW_HASH='\$6\$[A-Za-z0-9./]{6,}\$[A-Za-z0-9./]{20,}'

BASE_PATTERNS=(
  "private key block::$PRIV_BLOCK"
  "AWS access key::$AWS_KEY"
  "GitHub token::$GH_TOKEN"
  "Slack token::$SLACK_TOKEN"
  "unix password hash::$PW_HASH"
)

findings=0
hit() { findings=$((findings+1)); printf '  [!] %s\n' "$1"; }

echo "==> Secret scan — $(git rev-parse --short HEAD) ($(date '+%H:%M:%S'))"

echo
echo "-- 1. Working tree (tracked files, excluding configured paths) --"
for desc_pat in "${BASE_PATTERNS[@]}" "${EXTRA_PATTERNS[@]}"; do
  [ -z "$desc_pat" ] && continue
  desc=${desc_pat%%::*}; pat=${desc_pat#*::}
  out=$(git grep -nIE -e "$pat" -- "${EXCLUDE[@]}" 2>/dev/null)
  if [ -n "$out" ]; then hit "$desc:"; echo "$out" | sed 's/^/      /'; fi
done
[ "$findings" -eq 0 ] && echo "  clean"

echo
echo "-- 2. Encrypted-secret integrity --"
if [ -z "$ENCRYPTED_GLOB" ]; then
  echo "  skip — no encrypted-secret scheme configured for this project"
else
  intacterr=0
  any=0
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    any=1
    if grep -qE -e "$ENCRYPTED_MARKERS" "$f" 2>/dev/null; then
      echo "  ok   $f"
    else
      hit "UNENCRYPTED secret file: $f"; intacterr=1
    fi
  done < <(git ls-files "$ENCRYPTED_GLOB" 2>/dev/null)
  [ "$any" -eq 0 ] && echo "  no files matched $ENCRYPTED_GLOB"
  [ "$intacterr" -eq 0 ] && [ "$any" -eq 1 ] && echo "  all encrypted"
fi

echo
echo "-- 3. Git history (all commits, excluding configured paths) --"
if [ "$SCAN_HISTORY" != "yes" ]; then
  echo "  skip — history scan disabled for this project"
else
  echo "     (scanning $(git rev-list --all --count) commits; this can take a moment)"
  allrev=$(git rev-list --all)
  histhit=0
  for desc_pat in "${BASE_PATTERNS[@]}" "${EXTRA_PATTERNS[@]}"; do
    [ -z "$desc_pat" ] && continue
    desc=${desc_pat%%::*}; pat=${desc_pat#*::}
    # shellcheck disable=SC2086
    out=$(git grep -lIE -e "$pat" $allrev -- "${EXCLUDE[@]}" 2>/dev/null | head -20)
    if [ -n "$out" ]; then
      hit "$desc found in history (commit:path):"; echo "$out" | sed 's/^/      /'; histhit=1
    fi
  done
  [ "$histhit" -eq 0 ] && echo "  clean"
fi

echo
echo "-- 4. .gitignore coverage (informational) --"
if [ "${#GITIGNORE_PATTERNS[@]}" -eq 0 ]; then
  echo "  skip — no patterns configured"
else
  for p in "${GITIGNORE_PATTERNS[@]}"; do
    if grep -qF "$p" .gitignore 2>/dev/null; then echo "  ok   ignores $p"; else echo "  note missing $p in .gitignore"; fi
  done
fi

echo
if [ "$findings" -eq 0 ]; then
  echo "==> RESULT: clean — no plaintext secrets found in tree or history."
else
  echo "==> RESULT: $findings finding(s) — review above before pushing / publishing."
fi
